BATCH_SIZE: 128
GRAD_ACCUMULATION_STEPS: 2
MAX_EPOCHS: 20
Stage_classifier:
  dropout: 0.2
  hidden_dims:
  - 800
  - 400
  - 100
  input_dim: 1280
  num_classes: 7
callbacks:
  EarlyStopping:
    min_delta: 5.0e-05
    mode: min
    monitor: val_CE_loss
    patience: 8
  ModelCheckpoint:
    mode: min
    monitor: val_CE_loss
    save_last: true
    save_top_k: 1
ckpt_file_name: '{epoch}-{val_CE_loss:.2f}-{val_accuracy:.2f}'
lr: 1.0e-05
num_workers: 8
save_dir: results
weight_decay: 0.0001
