save_dir : "results"

Stage_classifier :
  input_dim : 1280
  num_classes : 4
  dropout : 0.2
  hidden_dims :
    - 800
    - 400
    - 100

BATCH_SIZE : 128
lr : 0.00001
weight_decay : 0.0001
MAX_EPOCHS : 20
GRAD_ACCUMULATION_STEPS : 2
num_workers : 8
ckpt_file_name: '{epoch}-{val_CE_loss:.2f}-{val_accuracy:.2f}'

# CALLBACK related config
callbacks:
  ModelCheckpoint:
    monitor: 'val_CE_loss'
    mode: 'min'
    save_top_k: 1
    save_last: True
  EarlyStopping:
    monitor: 'val_CE_loss'
    mode: 'min'
    min_delta : 0.00005
    patience : 8