method : 'bayes'
name : 'RepresentationLearning_sweep'
metric :
  goal : 'minimize'
  name : 'val_HuberLoss'

parameters :
    BATCH_SIZE :
      values : [32, 64, 128]
    denoisingAE_lr :
      min: 1e-4
      max: 2e-3
    sparseAE_lr :
      min: 8e-4
      max: 5e-3
    activation_name :
      values : ["relu", "leaky_relu", "prelu"]
    loss_fn :
      values: ['MSELoss', 'HuberLoss']
    weight_decay :
      min : 1e-6
      max : 5e-5
    GRAD_ACCUMULATION_STEPS :
      values : [1, 2]